config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    respond_to do |format|
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.' 
      else
        render :new 
      end
  end
end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render :edit 
      end
  end
end

  def destroy
    @pin.destroy
    respond_to do |format|
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "OzPinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
<% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="row-nogutter">
<img src="http://emergencylocksmithsanfrancisco.com/wp-content/uploads/2013/03/skyline.png" class=img-responsive>
<div class="panel panel-primary">
	<div class="panel-heading">
		<h1>About us</h1>
	</div>
	<div class="panel-body">
		<p class="lead">We are working on our One Month Rails Pinteresting app!  We're also learning how to do all kinds of crazy stuff in ruby on rails so we can hack together some wonky prototypes.  Meanwhile, we're also watching silly 80's movies starring Arnold Schwarznegger.</p>
		<h2 bold>Founders</h2>
		<div class="media">
		  <div class="media-left media-middle">
		    <a href="#">
		      <img class="media-object img-circle" src="https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10561561_10102484760926015_798387499557968626_n.jpg?oh=7d9e950bd8d9459a7c8635e0aa3558e9&oe=562FCDC6" height="150" width="150">
		    </a>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading">Derek Osgood</h4>
		    <p class="media-body limit">General purveyor of shenanigans with a penchant for causing a ruckus via accidentally misinterpretting "pinning" and actually pinning things to people.</p>
		  </div>
		</div>
		<h1></h1>
		  <div class="media-body">
		    <h4 class="media-heading text-right">Bill Brasky</h4>
		    <p class="media-body-right">A 10-foot mountain of a man who showers in vodka and feeds his baby shrimp scampi.</p>
		  </div>
		  	<div class="media-right media-middle">
		    <a href="#">
		      <img class="media-object img-circle" src="http://www.golfwrx.com/forums/uploads/profile/photo-92243.jpg?_r=1431982712" height="150" width="150">
		    </a>
		  </div>
		 <h1></h1>
		 <div class="media">
		  <div class="media-left media-middle">
		    <a href="#">
		      <img class="media-object img-circle" src="http://www.athletepromotions.com/blog/wp-content/uploads/2014/01/Brett-favre.jpg" height="150" width="150">
		    </a>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading">Brett Favre</h4>
		    <p class="media-body limit">Legend.  Gunslinger.  Lord of Wrangler Jeans.  Throws a football a country mile.  Eats bald eagles for breakfast.</p>
		  </div>
		</div>
		</div>
	<div class="panel-body center"
	<p><%= link_to "Email us for more info", "mailto:osgood.derek@gmail.com", class: "btn btn-success btn-lg" %></p>
</div>
	</div>
<div class="panel panel-primary">
	<div class="panel-heading">
		<h1>What we're about...</h1>
	</div>
		  <div class="embed-responsive embed-responsive-16by9">
			  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZTidn2dBYbY"></iframe>
			</div>
		</div>
	</div>
</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Go fuck yourself, San Diego!</h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
	<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	<% end %>
	</p>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>